### ISSUE TITLE
Error in logs of `dev` branch 

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#161]
This error does not appear on Sentry, but there are logs of POST to sentry.io 🤔

See logs attached to this file, with the following extract:
```
2022-02-11 13:42:21 [DEBUG] P2P.peers: New message received {'from': b'12D3KooWBfGpZ2zuAjtiSVEynYfCN6dHv5JkFe4m9qYov1uJcNeC', 'data': b'%7B%22address%22%3A%20%22/ip4/51.89.96.79/tcp/4025/p2p/QmYEro66g9xCr5hh57BtVcN32Ly7fxuG4mUuVn489PfgRz%22%2C%20%22interests%22%3A%20null%2C%20%22peer_type%22%3A%20%22P2P%22%2C%20%22version%22%3A%20%22v0.1.11%22%7D', 'seqno': b'\x16\xd0\xf2\xa2\xb8\xa6\x19Q', 'topicIDs': ['ALEPH_ALIVE']}
2022-02-11 13:42:21 [ERROR] P2P.peers: Exception in pubsub peers monitoring, resubscribing
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/aleph/services/peers/monitor.py", line 73, in monitor_hosts_p2p
    await read_pbmsg_safe(stream, pubsub_msg)
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/utils.py", line 25, in read_pbmsg_safe
    len_msg_bytes = await read_unsigned_varint(stream)
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/serialization.py", line 33, in read_unsigned_varint
    data = await stream.receive_exactly(1)
  File "/opt/venv/lib/python3.8/site-packages/anyio/_networking.py", line 250, in receive_exactly
    raise IncompleteRead
anyio.exceptions.IncompleteRead: The stream was closed before the read operation could be completed
2022-02-11 13:42:22 [ERROR] P2P.protocol: Exception in pubsub, reconnecting.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/aleph/services/p2p/protocol.py", line 195, in incoming_channel
    async for mvalue in sub(topic):
  File "/opt/venv/lib/python3.8/site-packages/aleph/services/p2p/pubsub.py", line 17, in sub
    await read_pbmsg_safe(stream, pubsub_msg)
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/utils.py", line 25, in read_pbmsg_safe
    len_msg_bytes = await read_unsigned_varint(stream)
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/serialization.py", line 33, in read_unsigned_varint
    data = await stream.receive_exactly(1)
  File "/opt/venv/lib/python3.8/site-packages/anyio/_networking.py", line 250, in receive_exactly
    raise IncompleteRead
anyio.exceptions.IncompleteRead: The stream was closed before the read operation could be completed
2022-02-11 13:42:22 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): o74683.ingest.sentry.io:443
2022-02-11 13:42:22 [ERROR] P2P.protocol: Exception in pubsub, reconnecting.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/anyio/__init__.py", line 345, in try_connect
    await sock.connect((addr, port))
  File "/opt/venv/lib/python3.8/site-packages/anyio/_networking.py", line 87, in connect
    raise OSError(error, errno.errorcode[error])
ConnectionRefusedError: [Errno 111] ECONNREFUSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/aleph/services/p2p/protocol.py", line 195, in incoming_channel
    async for mvalue in sub(topic):
  File "/opt/venv/lib/python3.8/site-packages/aleph/services/p2p/pubsub.py", line 14, in sub
    stream = await p2p_client.pubsub_subscribe(topic)
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/p2pclient.py", line 113, in pubsub_subscribe
    return await self.pubsub.subscribe(topic=topic)
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/pubsub.py", line 65, in subscribe
    stream = await self.daemon_connector.open_connection()
  File "/opt/venv/lib/python3.8/site-packages/p2pclient/control.py", line 59, in open_connection
    return await anyio.connect_tcp(address=host, port=port)
  File "/opt/venv/lib/python3.8/site-packages/anyio/__init__.py", line 404, in connect_tcp
    raise OSError('All connection attempts failed') from cause
OSError: All connection attempts failed
2022-02-11 13:42:22 [ERROR] P2P.protocol: Exception in pubsub, reconnecting.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/anyio/__init__.py", line 345, in try_connect
    await sock.connect((addr, port))
  File "/opt/venv/lib/python3.8/site-packages/anyio/_networking.py", line 87, in connect
    raise OSError(error, errno.errorcode[error])
ConnectionRefusedError: [Errno 111] ECONNREFUSED
```
[2022-02-11-docker-monitoring_pyaleph_1.log](https://github.com/aleph-im/pyaleph/files/8049060/2022-02-11-docker-monitoring_pyaleph_1.log)

**Comment by hoh** [comment]
Could this be related to this exception on the current version ?

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/network/swarm.py", line 200, in conn_handler
    muxed_conn = await self.upgrader.upgrade_connection(
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/transport/upgrader.py", line 57, in upgrade_connection
    raise MuxerUpgradeFailure(
libp2p.transport.exceptions.MuxerUpgradeFailure: failed to negotiate the multiplexer protocol

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/network/swarm.py", line 207, in conn_handler
    raise SwarmException(error_msg % peer_id) from error
libp2p.network.exceptions.SwarmException: fail to upgrade mux for peer Qmaxufiqdyt5uVWcy1Xh2nh3Rs3382ArnSP2umjCiNG2Vs
2022-02-11 13:55:24 [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='Task-47689' coro=<Swarm.listen.<locals>.conn_handler() done, defined at /opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/network/swarm.py:172> exception=SwarmException('fail to upgrade mux for peer Qmaxufiqdyt5uVWcy1Xh2nh3Rs3382ArnSP2umjCiNG2Vs')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/protocol_muxer/multiselect_communicator.py", line 33, in read
    data = await read_delim(self.read_writer)
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/utils.py", line 73, in read_delim
    msg_bytes = await read_varint_prefixed_bytes(reader)
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/utils.py", line 58, in read_varint_prefixed_bytes
    len_msg = await decode_uvarint_from_stream(reader)
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/utils.py", line 42, in decode_uvarint_from_stream
    byte = await read_exactly(reader, 1)
  File "/opt/venv/lib/python3.8/site-packages/libp2p-0.1.4-py3.8.egg/libp2p/io/utils.py", line 21, in read_exactly
    raise IncompleteReadError({"requested_count": n, "received_count": len(data)})
libp2p.io.exceptions.IncompleteReadError: {'requested_count': 1, 'received_count': 0}
```

**Comment by odesenfans** [comment]
There seems to be an issue causing the JS P2P daemon to fail and becoming unavailable for a short period of time. Here's the error in the logs of the P2P daemon:

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

I'll look into it, but that does not prevent the node from working as the pubsub connections are reset in case of error.

**Comment by odesenfans** [comment]
Should be resolved when we switch to the P2P service in production.
