### ISSUE TITLE
Problem: aiohttp server randomly crashes (assert transport is not None)

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/pyaleph#400]
The aiohttp server can crash randomly because of an invalid assertion in aiohttp code. The issue appears to be on the side of aiohttp and is tracked in the following Github issue: https://github.com/aio-libs/aiohttp/issues/6978.

**Logs**

> pyaleph-api_1  |   File "/opt/venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 446, in _make_request
pyaleph-api_1  |     return _cls(
pyaleph-api_1  |            ^^^^^
pyaleph-api_1  |   File "/opt/venv/lib/python3.11/site-packages/aiohttp/web_request.py", line 811, in __init__
pyaleph-api_1  |     super().__init__(*args, **kwargs)
pyaleph-api_1  |   File "/opt/venv/lib/python3.11/site-packages/aiohttp/web_request.py", line 188, in __init__
pyaleph-api_1  |     assert transport is not None
pyaleph-api_1  |            ^^^^^^^^^^^^^^^^^^^^^
pyaleph-api_1  | AssertionError
pyaleph-api_1  | ERROR:asyncio:Task exception was never retrieved
pyaleph-api_1  | future: <Task finished name='Task-53235' coro=<RequestHandler.start() done, defined at /opt/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py:462> exception=AssertionError()>
pyaleph-api_1  | Traceback (most recent call last):
pyaleph-api_1  |   File "/opt/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 505, in start
pyaleph-api_1  |     request = self._request_factory(message, payload, self, writer, handler)
pyaleph-api_1  |               

**Solution**

Wait for the next stable release of aiohttp once it is released, the bug should be fixed then.

**Comment by odesenfans** [comment]
Fixed by #406.
