### ISSUE TITLE
Sudden increase in Ethereum API queries

### ISSUE THREAD

**Issue by cryptarchnoble** [aleph-im/pyaleph#86]
I've attached a logs segment from the pyaleph container, where it seems to encounter a problem and enter a weird state. Metrics become unable to be queried, and the number of requests it makes to the Ethereum blockchain steeply increases. 

[logs.txt](https://github.com/aleph-im/pyaleph/files/5727215/logs.txt)

The relevant error seems to start on line 1346:

2020-12-21 23:05:55 [ERROR] P2P.HTTP: Error in retrieval
Traceback (most recent call last):
  File "/opt/pyaleph/src/aleph/services/p2p/http.py", line 29, in api_get_request
    result = await resp.json()
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1092, in json
    await self.read()
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 371, in read
    block = await self.readany()
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 393, in readany
    await self._wait("readany")
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 307, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

This error repeats multiple times per second, hundreds of thousands of times in the logs, until the node was restarted.

**Comment by cryptarchnoble** [comment]
I caught logs from another separate server that just started doing the same thing, within an hour of restart:

```nfm-000002-ALEPH-10022-pyaleph | 2020-12-22 04:47:42 [WARNING] JOBS: Can't reconnect to /dnsaddr/bootstrap.aleph.im/ipfs/QmPR8m8WCmYKuuxg5Qnadd4LbnTCD2L93cV2zPW5XGVHTG
nfm-000002-ALEPH-10022-pyaleph | Traceback (most recent call last):
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/bin/pyaleph", line 11, in <module>
nfm-000002-ALEPH-10022-pyaleph |     load_entry_point('pyaleph', 'console_scripts', 'pyaleph')()
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/pyaleph/src/aleph/commands.py", line 312, in run
nfm-000002-ALEPH-10022-pyaleph |     main(sys.argv[1:])
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/pyaleph/src/aleph/commands.py", line 307, in main
nfm-000002-ALEPH-10022-pyaleph |     loop.run_until_complete(asyncio.gather(*tasks))
nfm-000002-ALEPH-10022-pyaleph |   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
nfm-000002-ALEPH-10022-pyaleph |     return future.result()
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/pyaleph/src/aleph/services/ipfs/pubsub.py", line 58, in incoming_channel
nfm-000002-ALEPH-10022-pyaleph |     await incoming(message)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/pyaleph/src/aleph/chains/common.py", line 236, in incoming
nfm-000002-ALEPH-10022-pyaleph |     await Message.collection.bulk_write([action])
nfm-000002-ALEPH-10022-pyaleph |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
nfm-000002-ALEPH-10022-pyaleph |     result = self.fn(*self.args, **self.kwargs)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/pymongo-3.11.2-py3.8-linux-x86_64.egg/pymongo/collection.py", line 505, in bulk_write
nfm-000002-ALEPH-10022-pyaleph |     bulk_api_result = blk.execute(write_concern, session)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/pymongo-3.11.2-py3.8-linux-x86_64.egg/pymongo/bulk.py", line 528, in execute
nfm-000002-ALEPH-10022-pyaleph |     return self.execute_command(generator, write_concern, session)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/pymongo-3.11.2-py3.8-linux-x86_64.egg/pymongo/bulk.py", line 363, in execute_command
nfm-000002-ALEPH-10022-pyaleph |     _raise_bulk_write_error(full_result)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/pymongo-3.11.2-py3.8-linux-x86_64.egg/pymongo/bulk.py", line 140, in _raise_bulk_write_error
nfm-000002-ALEPH-10022-pyaleph |     raise BulkWriteError(full_result)
nfm-000002-ALEPH-10022-pyaleph | pymongo.errors.BulkWriteError: batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: aleph.messages index: item_hash_1_chain_1_sender_1_type_1 dup key: { : "9e096383bfb93f5ea07e92650722a4a3712264a50b17b57e533ebfa4f3cf6476", : "NULS2", : "NULSd6HgZu2PHzuMaVe4QGPfWuNhYRc1Xrvxu", : "POST" }', 'op': SON([('q', {'item_hash': '9e096383bfb93f5ea07e92650722a4a3712264a50b17b57e533ebfa4f3cf6476', 'chain': 'NULS2', 'sender': 'NULSd6HgZu2PHzuMaVe4QGPfWuNhYRc1Xrvxu', 'type': 'POST'}), ('u', {'$max': {'confirmed': False}, '$min': {'time': 1608612504.66}, '$set': {'content': {'type': 'file', 'address': 'NULSd6HgZu2PHzuMaVe4QGPfWuNhYRc1Xrvxu', 'content': {'filename': '0427f0f1cc27bc598ae1592f3139458fb05f9edb4c0ae60d04cc145295f7381cb45159f62e39bc834b192e3dceafc9963e0fa7d16a68c9abc7614ece63926d2a02cddaf27ce49e6fbcd8ae0d9e0ac623f192d42cba0840174ed7ca3552b72f76f544b48bbff6691dd4b6c3', 'mimetype': '04d0365b663aa42608a0355a5e758bff44ae9b1ff0050c01b9102c1864af43e2119edcbb3c9ac529a02cbd294f1cfc63d533117ef8592e7708e2b27c35646b1ae01956269159e894656711f40ca673f3495b5b527203014347bb0ac30815241b1c', 'private': True, 'store_message': '8dcc802d27958909d11eacc6630cd567f7ba9f5f277b9a285b733fc18c4127a5', 'hash': 'e82708b88e9eee699db8dc288f2f6324470691e5010b149122c20b9ec9b0720e', 'engine': 'storage', 'status': 'visible', 'size': 1436, 'full_size': 1533}, 'time': 1608612504.66, 'ref': '651f94c6ecba2bab2bd18b8251886f37c9eb83e5d6a3bd6db5b927cf30ad8f25'}, 'size': 846, 'item_content': '{"type":"file","address":"NULSd6HgZu2PHzuMaVe4QGPfWuNhYRc1Xrvxu","content":{"filename":"0427f0f1cc27bc598ae1592f3139458fb05f9edb4c0ae60d04cc145295f7381cb45159f62e39bc834b192e3dceafc9963e0fa7d16a68c9abc7614ece63926d2a02cddaf27ce49e6fbcd8ae0d9e0ac623f192d42cba0840174ed7ca3552b72f76f544b48bbff6691dd4b6c3","mimetype":"04d0365b663aa42608a0355a5e758bff44ae9b1ff0050c01b9102c1864af43e2119edcbb3c9ac529a02cbd294f1cfc63d533117ef8592e7708e2b27c35646b1ae01956269159e894656711f40ca673f3495b5b527203014347bb0ac30815241b1c","private":true,"store_message":"8dcc802d27958909d11eacc6630cd567f7ba9f5f277b9a285b733fc18c4127a5","hash":"e82708b88e9eee699db8dc288f2f6324470691e5010b149122c20b9ec9b0720e","engine":"storage","status":"visible","size":1436,"full_size":1533},"time":1608612504.66,"ref":"651f94c6ecba2bab2bd18b8251886f37c9eb83e5d6a3bd6db5b927cf30ad8f25"}', 'item_type': 'inline', 'channel': 'MYALEPH', 'signature': 'G2wvZqfqaWqJA+48OX4Gl5iaKf4zTcAbMrKU7nvOVxi2LG/GBs/VhJkGYyE6xZzY5YdSCBYls8wszLZP71OBLRc='}}), ('multi', False), ('upsert', True)])}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}
nfm-000002-ALEPH-10022-pyaleph | Error handling request
nfm-000002-ALEPH-10022-pyaleph | Traceback (most recent call last):
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
nfm-000002-ALEPH-10022-pyaleph |     resp = await self._request_handler(request)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/sentry_sdk-0.19.5-py3.8.egg/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
nfm-000002-ALEPH-10022-pyaleph |     reraise(*_capture_exception(hub))
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/sentry_sdk-0.19.5-py3.8.egg/sentry_sdk/_compat.py", line 54, in reraise
nfm-000002-ALEPH-10022-pyaleph |     raise value
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/sentry_sdk-0.19.5-py3.8.egg/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
nfm-000002-ALEPH-10022-pyaleph |     response = await old_handle(self, request)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
nfm-000002-ALEPH-10022-pyaleph |     resp = await handler(request)
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/pyaleph/src/aleph/web/controllers/main.py", line 80, in metrics_json
nfm-000002-ALEPH-10022-pyaleph |     return web.Response(text=(await get_metrics(shared_stats)).to_json(),
nfm-000002-ALEPH-10022-pyaleph |   File "/opt/pyaleph/src/aleph/web/controllers/metrics.py", line 161, in get_metrics
nfm-000002-ALEPH-10022-pyaleph |     pyaleph_processing_pending_messages_seen_ids_total=shared_stats.get('retry_messages_job_seen_ids'),
nfm-000002-ALEPH-10022-pyaleph |   File "<string>", line 2, in get
nfm-000002-ALEPH-10022-pyaleph |   File "/usr/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
nfm-000002-ALEPH-10022-pyaleph |     conn.send((self._id, methodname, args, kwds))
nfm-000002-ALEPH-10022-pyaleph |   File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
nfm-000002-ALEPH-10022-pyaleph |     self._send_bytes(_ForkingPickler.dumps(obj))
nfm-000002-ALEPH-10022-pyaleph |   File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
nfm-000002-ALEPH-10022-pyaleph |     self._send(header + buf)
nfm-000002-ALEPH-10022-pyaleph |   File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
nfm-000002-ALEPH-10022-pyaleph |     n = write(self._handle, buf)
nfm-000002-ALEPH-10022-pyaleph | BrokenPipeError: [Errno 32] Broken pipe```
